services:
- type: web
  name: leadsscrapertools
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python app.py"   # or main.py if your script name is main.py
  envVars:
    - key: SERPER_API_KEY
      sync: false
    - key: GOOGLE_SHEET_NAME
      sync: false
